### ISSUE TITLE
Character respawns at wrong place

### ISSUE THREAD

**Issue by sven-n** [MUnique/OpenMU#268]
**Describe the bug**
When a character dies, it respawns at the wrong place. For example at Devias 2 instead of Devias town.

**To Reproduce**
1. Enter the game with a (weak) character
2. Go to Icarus or Devias and let it die
3. It respawns at Devias 2

**Expected behavior**
It should respawn at Devias town

**Additional context**
To determine where a character respawns, the ExitGate has a property called "IsSpawnGate". The problem is, for the respawn logic it's basically true for too many gates - all which are listed in the warp menu.

Possible solution: Set it to true just for the safezone gates at the towns. Change the comment which describes the property.
They're initialized at _MUnique.OpenMU.Persistence.Initialization.Version*.Gates_.

**Comment by Fonzeca** [comment]
This are fixed? cannot reproduce the error

**Comment by sven-n** [comment]
I didn't fix it yet.
It might occur randomly, depending in which order the ExitGates were loaded from the database.

**Comment by Mosch0512** [comment]
I can reproduce this all the time with the basic configuration.

My guesses so far is but i am not sure that "config.ExitGate.IsSpawnGate" is not correctly set for all the maps?

**Comment by Mosch0512** [comment]
Is there an way to know what MapId belongs to the according map name?
![grafik](https://user-images.githubusercontent.com/48485443/206314105-434bcf13-a3be-47e0-9f49-f57a93c3e756.png)
